version: '3.4'
services:
  backend:
    build:
      context: ./ActivityApplication
      dockerfile: Dockerfile
    container_name: activityapplication_backend
    ports:
      - "8080:80"
    networks:
      - my_network

  frontend:
    build:
      context: ./ActivityApplication/ClientApp
      dockerfile: Dockerfile
    container_name: activityapplication_frontend
    ports:
      - "3000:3000"
    networks:
      - my_network
    environment:
      - REACT_APP_API_URL=http://activityapplication_backend:80/api/

networks:
  my_network:
    driver: bridge